Repository X-R-G-B/R-Bus, pull requests merged in 2023-09, with the labels that each got.

#5 Feature/RB 27 - Install deps
  .github/workflows/release.sh
  .github/workflows/release.yml
  CMakeLists.txt
  deps/CMakeLists.txt
  deps/asio/CMakeLists.txt
  deps/raylib/CMakeLists.txt
  src/poc/CMakeLists.txt
Labels: enhancement

#7 CICD: Fix warning cmake
  CMakeLists.txt
  deps/asio/CMakeLists.txt
  deps/raylib/CMakeLists.txt
Labels: bug

#6 Refactor/rb 23 refactor ecs
  CMakeLists.txt
  src/CMakeLists.txt
  src/Client/CMakeLists.txt
  src/Client/Systems/CMakeLists.txt
  src/Client/Systems/ClientSystems.cpp
  src/Client/Systems/ClientSystems.hpp
  src/Client/Systems/Managers/CMakeLists.txt
  src/Client/Systems/Managers/GraphicManager.cpp
  src/Client/Systems/Managers/GraphicManager.hpp
  src/Client/Systems/Managers/SystemEventsManager.cpp
  src/Client/Systems/Managers/SystemEventsManager.hpp
  src/ECS/CMakeLists.txt
  src/ECS/CustomTypes.hpp
  src/ECS/EventManager/CMakeLists.txt
  src/ECS/EventManager/EventManager.cpp
  src/ECS/EventManager/EventManager.hpp
  src/ECS/EventManager/Events.hpp
  src/ECS/Registry.cpp
  src/ECS/Registry.hpp
  src/ECS/SparseArray.hpp
  src/ECS/Systems/CMakeLists.txt
  src/ECS/Systems/Managers/ASystemManager.cpp
  src/ECS/Systems/Managers/ASystemManager.hpp
  src/ECS/Systems/Managers/CMakeLists.txt
  src/ECS/Systems/Managers/GameManager.cpp
  src/ECS/Systems/Managers/GameManager.hpp
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
  src/main.cpp
  src/poc/CMakeLists.txt
  src/poc/src/main.cpp
  src/poc/src/system/ASystem.cpp
  src/poc/src/system/ASystem.hpp
  src/poc/src/system/CMakeLists.txt
  src/poc/src/system/Collison.cpp
  src/poc/src/system/Collison.hpp
  src/poc/src/system/ISystem.hpp
  src/poc/src/system/Movement.cpp
  src/poc/src/system/Movement.hpp
  src/poc/src/system/PixelRenderer.cpp
  src/poc/src/system/PixelRenderer.hpp
  src/poc/src/system/managers/SystemManager.cpp
  src/poc/src/system/managers/SystemManager.hpp
Labels: refactor

#8 Dev
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/docs_improvement.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/performance_regression.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/pull_request_template.md
  .github/workflows/release.sh
  .github/workflows/release.yml
  .gitignore
  CMakeLists.txt
  deps/CMakeLists.txt
  deps/asio/CMakeLists.txt
  deps/raylib/CMakeLists.txt
  src/CMakeLists.txt
  src/Client/CMakeLists.txt
  src/Client/Systems/CMakeLists.txt
  src/Client/Systems/ClientSystems.cpp
  src/Client/Systems/ClientSystems.hpp
  src/Client/Systems/Managers/CMakeLists.txt
  src/Client/Systems/Managers/GraphicManager.cpp
  src/Client/Systems/Managers/GraphicManager.hpp
  src/Client/Systems/Managers/SystemEventsManager.cpp
  src/Client/Systems/Managers/SystemEventsManager.hpp
  src/ECS/CMakeLists.txt
  src/ECS/CustomTypes.hpp
  src/ECS/EventManager/CMakeLists.txt
  src/ECS/EventManager/EventManager.cpp
  src/ECS/EventManager/EventManager.hpp
  src/ECS/EventManager/Events.hpp
  src/ECS/Registry.cpp
  src/ECS/Registry.hpp
  src/ECS/SparseArray.hpp
  src/ECS/Systems/CMakeLists.txt
  src/ECS/Systems/Managers/ASystemManager.cpp
  src/ECS/Systems/Managers/ASystemManager.hpp
  src/ECS/Systems/Managers/CMakeLists.txt
  src/ECS/Systems/Managers/GameManager.cpp
  src/ECS/Systems/Managers/GameManager.hpp
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
  src/main.cpp
Labels: enhancement

#13 CICD: Fix bad auto bump version
  .github/workflows/release.sh
Labels: bug

#14 Feature/rb 16
  .clang-format
  .editorconfig
  .gitattributes
  .github/workflows/format.yml
  scripts/format.ps1
  scripts/format.sh
  src/Client/Systems/ClientSystems.cpp
  src/Client/Systems/Managers/GraphicManager.cpp
  src/Client/Systems/Managers/GraphicManager.hpp
  src/Client/Systems/Managers/SystemEventsManager.cpp
  src/Client/Systems/Managers/SystemEventsManager.hpp
  src/ECS/CustomTypes.hpp
  src/ECS/EventManager/EventManager.cpp
  src/ECS/EventManager/EventManager.hpp
  src/ECS/EventManager/Events.hpp
  src/ECS/Registry.cpp
  src/ECS/Registry.hpp
  src/ECS/SparseArray.hpp
  src/ECS/Systems/Managers/ASystemManager.cpp
  src/ECS/Systems/Managers/ASystemManager.hpp
  src/ECS/Systems/Managers/GameManager.cpp
  src/ECS/Systems/Managers/GameManager.hpp
  src/ECS/Systems/Systems.cpp
  src/main.cpp
Labels: enhancement

#11 CLIENT-GAME: Add system to print sprite and assets of R-Type
  assets/R-TypeSheet/r-typesheet1.gif
  assets/R-TypeSheet/r-typesheet10.gif
  assets/R-TypeSheet/r-typesheet11.gif
  assets/R-TypeSheet/r-typesheet12.gif
  assets/R-TypeSheet/r-typesheet13.gif
  assets/R-TypeSheet/r-typesheet14.gif
  assets/R-TypeSheet/r-typesheet16.gif
  assets/R-TypeSheet/r-typesheet17.gif
  assets/R-TypeSheet/r-typesheet18.gif
  assets/R-TypeSheet/r-typesheet19.gif
  assets/R-TypeSheet/r-typesheet2.gif
  assets/R-TypeSheet/r-typesheet20.gif
  assets/R-TypeSheet/r-typesheet21.gif
  assets/R-TypeSheet/r-typesheet22.gif
  assets/R-TypeSheet/r-typesheet23.gif
  assets/R-TypeSheet/r-typesheet24.gif
  assets/R-TypeSheet/r-typesheet25.gif
  assets/R-TypeSheet/r-typesheet26.gif
  assets/R-TypeSheet/r-typesheet27.gif
  assets/R-TypeSheet/r-typesheet28.gif
  assets/R-TypeSheet/r-typesheet29.gif
  assets/R-TypeSheet/r-typesheet3.gif
  assets/R-TypeSheet/r-typesheet30.gif
  assets/R-TypeSheet/r-typesheet30a.gif
  assets/R-TypeSheet/r-typesheet31.gif
  assets/R-TypeSheet/r-typesheet32.gif
  assets/R-TypeSheet/r-typesheet33.gif
  assets/R-TypeSheet/r-typesheet34.gif
  assets/R-TypeSheet/r-typesheet35.gif
  assets/R-TypeSheet/r-typesheet36.gif
  assets/R-TypeSheet/r-typesheet37.gif
  assets/R-TypeSheet/r-typesheet38.gif
  assets/R-TypeSheet/r-typesheet39.gif
  assets/R-TypeSheet/r-typesheet40.gif
  assets/R-TypeSheet/r-typesheet41.gif
  assets/R-TypeSheet/r-typesheet42.gif
  assets/R-TypeSheet/r-typesheet43.gif
  assets/R-TypeSheet/r-typesheet44.gif
  assets/R-TypeSheet/r-typesheet5.gif
  assets/R-TypeSheet/r-typesheet7.gif
  assets/R-TypeSheet/r-typesheet8.gif
  assets/R-TypeSheet/r-typesheet9.gif
  src/Client/Systems/ClientSystems.cpp
  src/Client/Systems/ClientSystems.hpp
  src/Client/Systems/CustomTypes.hpp
  src/Client/Systems/Managers/GraphicManager.cpp
  src/ECS/CustomTypes.hpp
  src/ECS/SparseArray.hpp
  src/ECS/Systems/Systems.cpp
  src/main.cpp
Labels: enhancement

#18 Feature/rb 17
  .clang-format
  .clang-tidy
  .github/workflows/compil.yml
  .github/workflows/format.yml
  .github/workflows/release.yml
  .gitignore
  CMakeLists.txt
  deps/asio/CMakeLists.txt
  deps/raylib/CMakeLists.txt
  scripts/compil.ps1
  scripts/compil.sh
  scripts/format.ps1
  scripts/format.sh
  src/CMakeLists.txt
  src/Client/CMakeLists.txt
  src/Client/Systems/CMakeLists.txt
  src/Client/Systems/ClientSystems.cpp
  src/Client/Systems/ClientSystems.hpp
  src/Client/Systems/Managers/CMakeLists.txt
  src/Client/Systems/Managers/GraphicManager.cpp
  src/Client/Systems/Managers/GraphicManager.hpp
  src/Client/Systems/Managers/SystemEventsManager.cpp
  src/Client/Systems/Managers/SystemEventsManager.hpp
  src/ECS/CMakeLists.txt
  src/ECS/EventManager/CMakeLists.txt
  src/ECS/EventManager/EventManager.cpp
  src/ECS/EventManager/EventManager.hpp
  src/ECS/EventManager/Events.hpp
  src/ECS/Registry.cpp
  src/ECS/Registry.hpp
  src/ECS/SparseArray.hpp
  src/ECS/Systems/CMakeLists.txt
  src/ECS/Systems/Managers/ASystemManager.hpp
  src/ECS/Systems/Managers/CMakeLists.txt
  src/ECS/Systems/Managers/GameManager.cpp
  src/ECS/Systems/Managers/GameManager.hpp
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
  src/main_client.cpp
  src/main_server.cpp
Labels: enhancement

#22 Feature/rb 15
  .github/workflows/compil.yml
  .github/workflows/format.yml
  .github/workflows/release.sh
  .github/workflows/release.yml
  .gitignore
  CMakeLists.txt
  LICENSE
  LICENSE.txt
  README.md
  assets/icons/favicon.bmp
  assets/icons/favicon.ico
  deps/CMakeLists.txt
  deps/asio/CMakeLists.txt
  deps/boost/CMakeLists.txt
  deps/raylib/CMakeLists.txt
  scripts/bundle-linux.sh
  scripts/bundle-macos.sh
  scripts/bundle-windows.ps1
  scripts/compil.ps1
  scripts/install-deps-linux.sh
  scripts/install-deps-macos.sh
  scripts/install-deps-windows.ps1
  src/main_client.cpp
  src/main_server.cpp
Labels: enhancement, CICD

#21 Feature/rb 37 text system
  assets/Fonts/soliden/SolidenTrial-Black.otf
  src/Client/Systems/ClientSystems.cpp
  src/Client/Systems/ClientSystems.hpp
  src/Client/Systems/CustomTypes.hpp
  src/Client/Systems/Managers/GraphicManager.cpp
  src/main_client.cpp
Labels: enhancement

#24 Feature/rb 49
  .github/workflows/compil.yml
  .github/workflows/documentation.yml
  CMakeLists.txt
  CONTRIBUTING.md
  README.md
  book.toml
  docs/CONTRIBUTING.md
  docs/README.md
  docs/SUMMARY.md
  docs/contributors.md
  docs/developer-guide/client/README.md
  docs/developer-guide/common-logic.md
  docs/developer-guide/ecs/README.md
  docs/developer-guide/ecs/uml.md
  docs/developer-guide/ecs/uml.png
  docs/developer-guide/network-rfc.md
  docs/developer-guide/network/README.md
  docs/developer-guide/network/rfc.md
  docs/developer-guide/server/README.md
  docs/screenshots.md
  docs/user-guide/installation/README.md
  docs/user-guide/installation/packaged-binary/README.md
  docs/user-guide/installation/packaged-binary/gnu-linux.md
  docs/user-guide/installation/packaged-binary/macos.md
  docs/user-guide/installation/packaged-binary/windows.md
  docs/user-guide/installation/source/README.md
  docs/user-guide/installation/source/gnu-linux.md
  docs/user-guide/installation/source/macos.md
  docs/user-guide/installation/source/windows.md
  docs/user-guide/troubleshooting.md
  docs/user-guide/usage.md
  scripts/bundle-linux.sh
  scripts/bundle-windows.ps1
Labels: documentation

#26 Feature/rb 52
  .github/workflows/compil.yml
  .github/workflows/documentation.yml
  .github/workflows/mirror.yml
  .github/workflows/release.yml
  CMakeLists.txt
  docs/SUMMARY.md
  docs/developer-guide/CICD.md
  docs/developer-guide/network-rfc.md
Labels: documentation, CICD

#27 DOCUMENTATION : Add new documentation to contribute to the project
  docs/CONTRIBUTING.md
Labels: documentation

#29 Feature/rb 41 registry additional sparse array
  src/Client/SceneManager.cpp
  src/Client/Systems/Events/EventsSystems.cpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Registry.cpp
  src/ECS/Registry.hpp
  src/ECS/Systems/Systems.cpp
Labels: enhancement

#32 Feature/rb 54 collision system
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Systems/Systems.cpp
Labels: enhancement
