Repository X-R-G-B/R-Bus, pull requests merged in 2023-10, with the labels that each got.

#35 DOCUMENTATION: Add raylib wrapper documentation
  docs/SUMMARY.md
  docs/developer-guide/client/README.md
  docs/developer-guide/client/audio/README.md
  docs/developer-guide/client/audio/audioSettings.md
  docs/developer-guide/client/audio/fileFormats.md
  docs/developer-guide/client/audio/music.md
  docs/developer-guide/client/audio/sounds.md
  docs/developer-guide/client/events/keyboard.md
  docs/developer-guide/client/events/mouse.md
  docs/developer-guide/client/geometry/color.md
  docs/developer-guide/client/geometry/rectangle.md
  docs/developer-guide/client/geometry/vector2.md
  docs/developer-guide/client/geometry/vector3.md
  docs/developer-guide/client/geometry/vector4.md
  docs/developer-guide/client/graphic/colorsPixels.md
  docs/developer-guide/client/graphic/configFlags.md
  docs/developer-guide/client/graphic/cursor.md
  docs/developer-guide/client/graphic/drawing.md
  docs/developer-guide/client/graphic/frameRate.md
  docs/developer-guide/client/graphic/image.md
  docs/developer-guide/client/graphic/misc.md
  docs/developer-guide/client/graphic/shapes.md
  docs/developer-guide/client/graphic/sprite.md
  docs/developer-guide/client/graphic/text.md
  docs/developer-guide/client/graphic/window.md
Labels: documentation

#42 ECS: Fix bad any cast
  src/ECS/Registry.cpp
Labels: bug

#40 CLIENT-GAME: Add clock for all the ECS
  docs/developer-guide/ecs/clock.md
  src/ECS/CMakeLists.txt
  src/ECS/Clock.cpp
  src/ECS/Clock.hpp
  src/ECS/Registry.cpp
  src/ECS/Registry.hpp
Labels: enhancement

#38 Feature/rb 56 check deads
  src/Client/Systems/Graphic/AudioSystems.cpp
  src/Client/Systems/Graphic/CMakeLists.txt
  src/Client/Systems/Graphic/DeathSystems.cpp
  src/Client/Systems/Graphic/DeathSystems.hpp
  src/Client/Systems/Graphic/GraphicSystems.cpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/SparseArray.hpp
  src/ECS/Systems/Systems.cpp
Labels: enhancement

#44 ECS: Add logger
  src/ECS/CMakeLists.txt
  src/ECS/Logger.cpp
  src/ECS/Logger.hpp
  src/ECS/Registry.cpp
  src/ECS/Registry.hpp
  src/main_client.cpp
Labels: enhancement

#46 CLIENT-GAME: Fix collision rect
  src/ECS/Systems/Systems.cpp
Labels: bug

#43 Feature/rb 22 network
  .clang-format
  .clang-tidy
  .github/workflows/compil.yml
  .gitignore
  CMakeLists.txt
  docs/network/rfc/client.md
  scripts/compil.ps1
  scripts/install-deps-linux.sh
  src/CMakeLists.txt
  src/Client/EventManager/EventManager.cpp
  src/Client/Raylib/Geometry/Geometry.cpp
  src/Client/Raylib/Graphics/Graphics.cpp
  src/Client/Raylib/Graphics/Graphics.hpp
  src/Client/SceneManager.cpp
  src/Client/Systems/ClientSystems.cpp
  src/Client/Systems/ClientSystems.hpp
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Events/EventsSystems.hpp
  src/Client/Systems/Graphic/AudioSystems.cpp
  src/Client/Systems/Graphic/AudioSystems.hpp
  src/Client/Systems/Graphic/DeathSystems.cpp
  src/Client/Systems/Graphic/DeathSystems.hpp
  src/Client/Systems/Graphic/GraphicSystems.cpp
  src/Client/Systems/Graphic/GraphicSystems.hpp
  src/Client/Systems/Graphic/SpriteSystems.cpp
  src/Client/Systems/Graphic/SpriteSystems.hpp
  src/Client/Systems/Graphic/TextSystems.cpp
  src/Client/Systems/Graphic/TextSystems.hpp
  src/ECS/Logger.cpp
  src/ECS/Logger.hpp
  src/ECS/Registry.cpp
  src/ECS/Registry.hpp
  src/ECS/SparseArray.hpp
  src/ECS/Systems/Managers/SystemManager.cpp
  src/ECS/Systems/Managers/SystemManager.hpp
  src/ECS/Systems/Managers/SystemManagersDirector.cpp
  src/ECS/Systems/Managers/SystemManagersDirector.hpp
  src/ECS/Systems/Systems.cpp
  src/Nitwork/ANitwork.cpp
  src/Nitwork/ANitwork.hpp
  src/Nitwork/CMakeLists.txt
  src/Nitwork/INitwork.hpp
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkServer.cpp
  src/Nitwork/NitworkServer.hpp
  src/main_client.cpp
  src/main_server.cpp
Labels: enhancement

#49 Fix/rb 73 events work with clocks
  src/Client/CMakeLists.txt
  src/Client/EventManager/CMakeLists.txt
  src/Client/EventManager/EventManager.cpp
  src/Client/EventManager/EventManager.hpp
  src/Client/EventManager/Events.hpp
  src/Client/SceneManager.cpp
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Graphic/SpriteSystems.cpp
  src/ECS/Clock.cpp
  src/ECS/Clock.hpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Systems/Systems.cpp
Labels: enhancement

#50 CLIENT-GAME: Fix graphic text system
  src/Client/Raylib/Graphics/Graphics.cpp
  src/Client/Raylib/Graphics/Graphics.hpp
  src/Client/Systems/CustomTypes.hpp
  src/Client/Systems/Graphic/TextSystems.cpp
  src/ECS/Systems/Systems.cpp
Labels: bug

#48 Feature/rb 59 parallax system
  assets/Json/parallaxData.json
  assets/Json/playerData.json
  assets/Map/Planets/Earth.png
  assets/Map/preview.png
  deps/CMakeLists.txt
  deps/json/CMakeLists.txt
  src/Client/Systems/CustomTypes.hpp
  src/Client/Systems/Events/EventsSystems.cpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Systems/Managers/SystemManager.cpp
  src/ECS/Systems/Managers/SystemManager.hpp
  src/ECS/Systems/Systems.cpp
  src/main_client.cpp
Labels: enhancement

#52 ECS: Add now useless entities outside the window are destroyed
  assets/Json/parallaxData.json
  src/Client/Systems/Events/EventsSystems.cpp
  src/ECS/Systems/Systems.cpp
Labels: enhancement

#54 Feature/rb 90 respond life update
  src/CMakeLists.txt
  src/ECS/ECSCustomTypes.hpp
  src/Nitwork/ANitwork.cpp
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkServer.cpp
  src/Nitwork/NitworkServer.hpp
  src/Server/CMakeLists.txt
  src/Server/Systems/CMakeLists.txt
  src/Server/Systems/ServerNetwork.cpp
  src/Server/Systems/ServerNetwork.hpp
Labels: enhancement

#55 Feature/rb 93
  deps/json/CMakeLists.txt
  src/Client/Systems/ClientSystems.cpp
  src/Client/Systems/ClientSystems.hpp
  src/Client/Systems/Network/ClientNetwork.cpp
  src/Client/Systems/Network/ClientNetwork.hpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/MessageTypes.h
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
Labels: enhancement

#47 Fix/rb 66 sound effect still playing
  CMakeLists.txt
  src/Client/Raylib/Audio/Audio.cpp
  src/Client/Raylib/Audio/Audio.hpp
  src/Client/Raylib/CMakeLists.txt
  src/Client/Raylib/UnloadRaylib.cpp
  src/Client/SceneManager.cpp
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Graphic/AudioSystems.cpp
  src/Client/Systems/Graphic/AudioSystems.hpp
  src/ECS/Registry.cpp
  src/ECS/Registry.hpp
  src/ECS/SparseArray.hpp
  src/ECS/Systems/Systems.cpp
Labels: bug

#60 CLIENT-GAME: Add wave management with initWave
  src/ECS/Systems/Systems.cpp
Labels: enhancement

#61 CLIENT-GAME: Modif now wave respect the number of ennemies to spawn
  src/ECS/Systems/Systems.cpp
Labels: bug, enhancement

#63 Doc/rb 105 logger doc
  docs/SUMMARY.md
  docs/developer-guide/ecs/logger.md
Labels: documentation

#65 ECS: Add windows terminal colors
  src/ECS/Logger.cpp
  src/ECS/Logger.hpp
Labels: enhancement

#70 ECS: Fix loss of fps when we reset scene
  src/ECS/Registry.cpp
Labels: bug

#62 Feature/rb 67
  assets/Json/playerData.json
  src/Client/Raylib/Audio/Audio.hpp
  src/Client/Raylib/Events/Inputs.hpp
  src/Client/Raylib/Geometry/Geometry.hpp
  src/Client/Raylib/Graphics/Graphics.hpp
  src/Client/Systems/CustomTypes.hpp
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Graphic/CMakeLists.txt
  src/Client/Systems/Graphic/GraphicSystems.cpp
  src/Client/Systems/Graphic/ParallaxSystems.cpp
  src/Client/Systems/Graphic/ParallaxSystems.hpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Registry.cpp
  src/ECS/Systems/Systems.cpp
Labels: enhancement

#53 Feature/rb 92 function receive enemy death
  src/Client/Systems/Network/ClientNetwork.cpp
  src/Client/Systems/Network/ClientNetwork.hpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/MessageTypes.h
  src/ECS/Registry.cpp
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkServer.cpp
Labels: enhancement

#64 CLIENT-NETWORK: Add send absolute position
  src/Client/Systems/Network/ClientNetwork.cpp
  src/ECS/MessageTypes.h
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
Labels: enhancement

#68 Server-network: Add send bullet function into bullet creation system
  src/Client/Systems/Events/EventsSystems.cpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Logger.hpp
  src/ECS/MessageTypes.h
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
Labels: enhancement

#71 Feature/rb 83 add init and start to client network
  src/Nitwork/ANitwork.cpp
  src/Nitwork/ANitwork.hpp
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkServer.cpp
  src/main_client.cpp
Labels: enhancement

#69 Feature/rb 87 system send life update
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Registry.cpp
  src/ECS/Systems/Systems.cpp
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
Labels: enhancement

#66 Feature/rb 82 respond to client enemy death
  src/Client/Systems/Network/ClientNetwork.cpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/MessageTypes.h
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkServer.cpp
  src/Nitwork/NitworkServer.hpp
  src/Server/Systems/Network/ServerNetwork.cpp
  src/Server/Systems/Network/ServerNetwork.hpp
Labels: enhancement

#75 Fix/rb 112 fix network stop blocked by threads
  src/Nitwork/ANitwork.cpp
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkServer.hpp
  src/main_server.cpp
Labels: bug

#76 CLIENT-NETWORK/SERVER-NETWORK: Add init receive by server and send init
  .github/workflows/format.yml
  src/Client/Systems/Network/ClientNetwork.cpp
  src/Client/Systems/Network/ClientNetwork.hpp
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkServer.cpp
  src/Nitwork/NitworkServer.hpp
Labels: enhancement

#73 Feature/rb 81 system send enemy death
  src/ECS/Systems/Systems.cpp
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
Labels: enhancement

#77 NITWORK: Remove std::cout
  src/Nitwork/ANitwork.hpp
  src/Nitwork/NitworkServer.cpp
Labels: enhancement

#74 CLIENT-NETWORK: Add receive enemy nb
  src/Client/SceneManager.cpp
  src/Client/SceneManager.hpp
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Network/ClientNetwork.cpp
  src/Client/Systems/Network/ClientNetwork.hpp
  src/ECS/CMakeLists.txt
  src/ECS/ECSCustomTypes.cpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
  src/Nitwork/ANitwork.hpp
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkServer.cpp
  src/Nitwork/NitworkServer.hpp
  src/main_client.cpp
Labels: enhancement

#78 Rb 101 adjust movements with clocks
  src/ECS/Systems/Systems.cpp
  src/main_client.cpp
Labels: enhancement

#79 CLIENT-NETWORK: Add function receive new enemy
  src/Client/Systems/Network/ClientNetwork.cpp
  src/Client/Systems/Network/ClientNetwork.hpp
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.hpp
  src/Server/Systems/Network/ServerNetwork.cpp
Labels: enhancement

#80 Fix/missing network send calls
  assets/Json/enemyData.json
  src/Client/Systems/Graphic/AudioSystems.cpp
  src/Client/Systems/Graphic/DeathSystems.cpp
  src/Client/Systems/Graphic/GraphicSystems.cpp
  src/Client/Systems/Graphic/ParallaxSystems.cpp
  src/Client/Systems/Graphic/SpriteSystems.cpp
  src/Client/Systems/Graphic/SpriteSystems.hpp
  src/Client/Systems/Network/ClientNetwork.cpp
  src/Client/Systems/Network/ClientNetwork.hpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Registry.hpp
  src/ECS/SparseArray.hpp
  src/ECS/Systems/Managers/SystemManager.cpp
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkServer.cpp
  src/Nitwork/NitworkServer.hpp
  src/Server/Systems/Network/ServerNetwork.cpp
  src/main_client.cpp
  src/main_server.cpp
Labels: enhancement

#81 SERVER-NETWORK/CLIENT-NETWORK: Change how packets are sent
  src/Nitwork/ANitwork.cpp
  src/Nitwork/ANitwork.hpp
  src/Nitwork/INitwork.hpp
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkServer.cpp
  src/Nitwork/NitworkServer.hpp
Labels: enhancement

#83 SERVER-NETWORK/CLIENT-NETWORK: Fix wrong id sent to the order side of…
  src/ECS/Systems/Systems.cpp
  src/Nitwork/NitworkServer.cpp
Labels: bug

#82 Feature/rb 111 singletone json
  src/Client/Systems/Graphic/ParallaxSystems.cpp
  src/Client/Systems/Network/ClientNetwork.cpp
  src/ECS/CMakeLists.txt
  src/ECS/Json.cpp
  src/ECS/Json.hpp
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
Labels: enhancement

#86 SERVER-NETWORK/CLIENT-NETWORK: Add receive new bullet to server and
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Events/EventsSystems.hpp
  src/Client/Systems/Graphic/SpriteSystems.cpp
  src/Client/Systems/Network/ClientNetwork.cpp
  src/Client/Systems/Network/ClientNetwork.hpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
  src/Nitwork/ANitwork.cpp
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkServer.cpp
  src/Nitwork/NitworkServer.hpp
  src/Server/Systems/Network/ServerNetwork.cpp
  src/Server/Systems/Network/ServerNetwork.hpp
Labels: enhancement

#88 NITWORK: Fix nitwork iad and packt lost handling
  src/Client/Systems/Graphic/DeathSystems.cpp
  src/Nitwork/ANitwork.cpp
  src/Nitwork/ANitwork.hpp
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkServer.cpp
Labels: bug

#89 CLIENT-GAME: Fix errors logs that wasn't errors
  src/Client/Systems/Graphic/ParallaxSystems.cpp
  src/ECS/Json.cpp
  src/ECS/Json.hpp
Labels: bug

#90 CLIENT-GAME: Fix missing add of network systems to the SceneManager
  src/Client/SceneManager.hpp
  src/Client/Systems/Network/ClientNetwork.cpp
Labels: bug

#91 Feature/rb 94
  src/ECS/MessageTypes.h
  src/Nitwork/ANitwork.cpp
  src/Nitwork/ANitwork.hpp
  src/Nitwork/INitwork.hpp
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkServer.cpp
  src/Nitwork/NitworkServer.hpp
Labels: enhancement

#95 Fix/rb 119 fix json
  assets/Json/enemyData.json
  src/Client/Systems/Graphic/ParallaxSystems.cpp
  src/ECS/Json.cpp
  src/ECS/Json.hpp
  src/ECS/Systems/Systems.cpp
Labels: bug

#87 CLIENT-NETWORK: Add receive other player
  src/Client/Systems/Network/ClientNetwork.cpp
  src/Client/Systems/Network/ClientNetwork.hpp
  src/ECS/MessageTypes.h
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.hpp
Labels: enhancement

#92 Doc/rb 104 json doc
  docs/SUMMARY.md
  docs/developer-guide/ecs/json/README.md
  docs/developer-guide/ecs/json/json.md
  src/ECS/Json.cpp
  src/ECS/Json.hpp
Labels: documentation

#94 NITWORK/DOCUMENTAION: rfc
  docs/network/rfc/RFC.md
  src/Client/Systems/Network/ClientNetwork.cpp
  src/ECS/MessageTypes.h
  src/Nitwork/ANitwork.cpp
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkServer.cpp
Labels: documentation

#96 CLIENT-GAME: Fix clock decrease instead of restart
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Graphic/SpriteSystems.cpp
  src/Client/Systems/Network/ClientNetwork.cpp
  src/ECS/Clock.cpp
  src/ECS/Clock.hpp
  src/ECS/Systems/Systems.cpp
  src/Nitwork/Nitwork.h
  src/main_client.cpp
Labels: bug

#97 Feat/resource manager
  .github/workflows/release.yml
  .gitignore
  CMakeLists.txt
  deps/boost/CMakeLists.txt
  docs/user-guide/installation/source/windows.md
  scripts/bundle-linux.sh
  scripts/bundle-macos.sh
  scripts/bundle-windows.ps1
  scripts/compil.sh
  scripts/install-deps-windows.ps1
  src/Client/Raylib/Audio/Audio.cpp
  src/Client/Raylib/Audio/Audio.hpp
  src/Client/Raylib/Graphics/Graphics.cpp
  src/ECS/CMakeLists.txt
  src/ECS/Json.cpp
  src/ECS/Json.hpp
  src/ECS/ResourcesManager.cpp
  src/ECS/ResourcesManager.hpp
  src/main_client.cpp
  src/main_server.cpp
Labels: enhancement

#98 SERVER-NETWORK: Add receive system for absolute position
  docs/network/rfc/RFC.md
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkServer.cpp
  src/Nitwork/NitworkServer.hpp
  src/Server/Systems/Network/ServerNetwork.cpp
  src/Server/Systems/Network/ServerNetwork.hpp
Labels: enhancement

#101 CLIENT-GAME: Add boss when wave ends
  assets/Json/terminator.json
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Json.hpp
  src/ECS/Systems/Systems.cpp
Labels: enhancement

#100 NITWORK: Fix packet id doesn't need to change if he's resent
  docs/network/rfc/RFC.md
  src/Nitwork/ANitwork.cpp
  src/Nitwork/ANitwork.hpp
  src/Nitwork/INitwork.hpp
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkServer.cpp
  src/Nitwork/NitworkServer.hpp
  src/main_client.cpp
  src/main_server.cpp
Labels: bug

#102 CLIENT-NETWORK: Fix cache not used spam relative
  src/Client/Systems/Network/ClientNetwork.cpp
Labels: enhancement

#104 CLIENT-NETWORK: Add system receive broadcast position absolute
  src/Client/Systems/Network/ClientNetwork.cpp
  src/Client/Systems/Network/ClientNetwork.hpp
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkServer.hpp
Labels: enhancement

#99 Rb 123 fix random bullet out of bound
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Graphic/AudioSystems.cpp
  src/Client/Systems/Graphic/ParallaxSystems.cpp
  src/Client/Systems/Graphic/SpriteSystems.cpp
  src/ECS/Systems/Systems.cpp
Labels: bug

#103 Fix/rb 133 change to real player
  assets/Json/playerData.json
  src/Client/Systems/Network/ClientNetwork.cpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Json.hpp
  src/ECS/MessageTypes.h
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
Labels: enhancement

#106 Feature/rb 118 system receive broadcast position relative
  src/Client/Systems/Network/ClientNetwork.cpp
  src/Client/Systems/Network/ClientNetwork.hpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Systems/Systems.cpp
  src/Nitwork/ANitwork.cpp
  src/Nitwork/ANitwork.hpp
  src/Nitwork/INitwork.hpp
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkServer.cpp
  src/Nitwork/NitworkServer.hpp
  src/main_server.cpp
Labels: enhancement

#107 dev -> main
  .github/workflows/release.yml
  .gitignore
  CMakeLists.txt
  assets/Json/enemyData.json
  assets/Json/playerData.json
  assets/Json/terminator.json
  deps/boost/CMakeLists.txt
  docs/SUMMARY.md
  docs/developer-guide/ecs/json/README.md
  docs/developer-guide/ecs/json/json.md
  docs/network/rfc/RFC.md
  docs/user-guide/installation/source/windows.md
  scripts/bundle-linux.sh
  scripts/bundle-macos.sh
  scripts/bundle-windows.ps1
  scripts/compil.sh
  scripts/install-deps-windows.ps1
  src/Client/Raylib/Audio/Audio.cpp
  src/Client/Raylib/Audio/Audio.hpp
  src/Client/Raylib/Graphics/Graphics.cpp
  src/Client/SceneManager.cpp
  src/Client/SceneManager.hpp
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Events/EventsSystems.hpp
  src/Client/Systems/Graphic/AudioSystems.cpp
  src/Client/Systems/Graphic/GraphicSystems.cpp
  src/Client/Systems/Graphic/ParallaxSystems.cpp
  src/Client/Systems/Graphic/SpriteSystems.cpp
  src/Client/Systems/Graphic/SpriteSystems.hpp
  src/Client/Systems/Network/ClientNetwork.cpp
  src/Client/Systems/Network/ClientNetwork.hpp
  src/ECS/CMakeLists.txt
  src/ECS/Clock.cpp
  src/ECS/Clock.hpp
  src/ECS/ECSCustomTypes.cpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Json.cpp
  src/ECS/Json.hpp
  src/ECS/MessageTypes.h
  src/ECS/Registry.hpp
  src/ECS/ResourcesManager.cpp
  src/ECS/ResourcesManager.hpp
  src/ECS/SparseArray.hpp
  src/ECS/Systems/Managers/SystemManager.cpp
  src/ECS/Systems/Managers/SystemManager.hpp
  src/ECS/Systems/Managers/SystemManagersDirector.hpp
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
  src/Nitwork/ANitwork.cpp
  src/Nitwork/ANitwork.hpp
  src/Nitwork/INitwork.hpp
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkServer.cpp
  src/Nitwork/NitworkServer.hpp
  src/Server/Systems/Network/ServerNetwork.cpp
  src/Server/Systems/Network/ServerNetwork.hpp
  src/main_client.cpp
  src/main_server.cpp
Labels: documentation, enhancement

#108 CLIENT-GAME: Fix sounds
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Graphic/AudioSystems.cpp
Labels: bug

#105 Feature/rb 135 spawn random of ennemies
  assets/Json/enemyData.json
  assets/Json/terminator.json
  assets/Json/wave.json
  src/Client/Systems/Graphic/SpriteSystems.cpp
  src/Client/Systems/Network/ClientNetwork.cpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Json.cpp
  src/ECS/Json.hpp
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
Labels: enhancement

#110 GAME: Add parallax nrv
  assets/Json/parallaxData.json
  assets/Map/Planets/Asteroid.png
  assets/Map/Planets/planet_1.png
  assets/Map/Planets/planet_2.png
  assets/Map/Planets/planet_3.png
  assets/Map/Planets/planet_4.png
  assets/Map/black-background.png
  assets/Map/layer1-1.png
  assets/Map/layer1-2.png
  assets/Map/layer2-1.png
  assets/Map/layer2-2.png
  assets/Map/layer3-1.png
  assets/Map/layer3-2.png
  assets/Map/layer4-1.png
  assets/Map/layer4-2.png
Labels: enhancement

#111 Dev to main
  .github/workflows/release.sh
  assets/Json/enemyData.json
  assets/Json/parallaxData.json
  assets/Json/terminator.json
  assets/Json/wave.json
  assets/Map/Planets/Asteroid.png
  assets/Map/Planets/planet_1.png
  assets/Map/Planets/planet_2.png
  assets/Map/Planets/planet_3.png
  assets/Map/Planets/planet_4.png
  assets/Map/black-background.png
  assets/Map/layer1-1.png
  assets/Map/layer1-2.png
  assets/Map/layer2-1.png
  assets/Map/layer2-2.png
  assets/Map/layer3-1.png
  assets/Map/layer3-2.png
  assets/Map/layer4-1.png
  assets/Map/layer4-2.png
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Graphic/AudioSystems.cpp
  src/Client/Systems/Graphic/SpriteSystems.cpp
  src/Client/Systems/Network/ClientNetwork.cpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Json.cpp
  src/ECS/Json.hpp
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
Labels: enhancement

#113 DOCUMENTATION: Add maths doc
  docs/SUMMARY.md
  docs/developer-guide/ecs/maths.md
Labels: documentation

#114 Fix/rb 141 fix last release problem
  src/Client/SceneManager.cpp
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Graphic/AudioSystems.cpp
  src/Client/Systems/Graphic/DeathSystems.cpp
  src/Client/Systems/Graphic/ParallaxSystems.cpp
  src/Client/Systems/Graphic/SpriteSystems.cpp
  src/Client/Systems/Graphic/TextSystems.cpp
  src/Client/Systems/Network/ClientNetwork.cpp
  src/ECS/Json.hpp
  src/ECS/Systems/Managers/SystemManager.cpp
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
  src/Nitwork/NitworkServer.cpp
  src/main_server.cpp
Labels: bug, enhancement

#112 Feature/rb 97 float to int
  assets/Json/enemyData.json
  assets/Json/parallaxData.json
  assets/Json/playerData.json
  assets/Json/terminator.json
  assets/Json/wave.json
  src/Client/Systems/CustomTypes.hpp
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Graphic/GraphicSystems.cpp
  src/Client/Systems/Graphic/ParallaxSystems.cpp
  src/Client/Systems/Graphic/SpriteSystems.cpp
  src/Client/Systems/Graphic/TextSystems.cpp
  src/Client/Systems/Network/ClientNetwork.cpp
  src/ECS/CMakeLists.txt
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Maths/CMakeLists.txt
  src/ECS/Maths/Maths.cpp
  src/ECS/Maths/Maths.hpp
  src/ECS/Systems/Systems.cpp
  src/Server/Systems/Network/ServerNetwork.cpp
Labels: enhancement

#116 ECS: Fix game boss movements
  src/ECS/Systems/Systems.cpp
Labels: bug

#118 CICD: Add zstd.tar to release
  .github/workflows/release.yml
Labels: CICD

#117 NITWORK/SERVER-NETWORK: Fix wrong implementation of tick and receiveClientEnemyDeath
  src/Nitwork/ANitwork.cpp
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkServer.hpp
  src/Server/Systems/Network/ServerNetwork.cpp
  src/main_client.cpp
  src/main_server.cpp
Labels: enhancement

#115 Feature/rb 143 compression pack network
  .github/workflows/compil.yml
  deps/CMakeLists.txt
  deps/boost/CMakeLists.txt
  deps/date/CMakeLists.txt
  deps/json/CMakeLists.txt
  deps/raylib/CMakeLists.txt
  deps/zstd/CMakeLists.txt
  docs/network/rfc/RFC.md
  scripts/compil.sh
  src/Nitwork/ANitwork.cpp
  src/Nitwork/ANitwork.hpp
  src/Nitwork/Zstd.hpp
Labels: enhancement

#122 Feature/rb 147 plusieurs type de balle
  CMakeLists.txt
  assets/Json/bullets.json
  assets/R-TypeSheet/FireBullets.png
  assets/R-TypeSheet/GreenBullets.png
  assets/R-TypeSheet/PurpleBullets.png
  assets/R-TypeSheet/WaterBullets.png
  docs/developer-guide/ecs/json/json.md
  docs/developer-guide/ecs/maths.md
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Graphic/AudioSystems.cpp
  src/ECS/ECSCustomTypes.hpp
  src/ECS/Json.cpp
  src/ECS/Json.hpp
  src/ECS/Maths/Maths.cpp
  src/ECS/Maths/Maths.hpp
  src/ECS/MessageTypes.h
  src/ECS/Systems/BulletsSystems.cpp
  src/ECS/Systems/CMakeLists.txt
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
  src/Nitwork/ANitwork.hpp
Labels: enhancement

#121 Feature/rb 148 generic anim rect
  assets/Json/bullets.json
  assets/Json/enemyData.json
  assets/Json/playerData.json
  assets/Json/terminator.json
  src/Client/Systems/CMakeLists.txt
  src/Client/Systems/CustomTypes.hpp
  src/Client/Systems/CustomTypes/AnimRect.cpp
  src/Client/Systems/CustomTypes/AnimRect.hpp
  src/Client/Systems/CustomTypes/CMakeLists.txt
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Graphic/DeathSystems.cpp
  src/Client/Systems/Graphic/SpriteSystems.cpp
  src/Client/Systems/Graphic/SpriteSystems.hpp
  src/ECS/Systems/BulletsSystems.cpp
  src/ECS/Systems/Systems.cpp
Labels: enhancement

#124 Feature/rb 136 other player distroyed when player die
  docs/network/rfc/RFC.md
  docs/network/rfc/client.md
  src/Client/Systems/Graphic/DeathSystems.cpp
  src/Client/Systems/Network/ClientNetwork.cpp
  src/Client/Systems/Network/ClientNetwork.hpp
  src/ECS/Systems/Systems.cpp
  src/ECS/Systems/Systems.hpp
  src/Nitwork/ANitwork.cpp
  src/Nitwork/ANitwork.hpp
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkServer.cpp
  src/Nitwork/NitworkServer.hpp
  src/Nitwork/Zstd.hpp
  src/Server/Systems/Network/ServerNetwork.cpp
  src/Server/Systems/Network/ServerNetwork.hpp
Labels: enhancement

#127 Fix/missile pos other clients
  src/Client/Systems/Events/EventsSystems.cpp
  src/ECS/Systems/BulletsSystems.cpp
  src/ECS/Systems/Systems.hpp
Labels: bug

#129 Feature/rb 142 menu de connection
  assets/Json/menu.json
  docs/developer-guide/client/graphic/text.md
  docs/developer-guide/ecs/json/json.md
  src/Client/Raylib/Events/Inputs.hpp
  src/Client/Raylib/Graphics/Graphics.cpp
  src/Client/Raylib/Graphics/Graphics.hpp
  src/Client/SceneManager.hpp
  src/Client/Systems/CMakeLists.txt
  src/Client/Systems/ClientSystems.cpp
  src/Client/Systems/ClientSystems.hpp
  src/Client/Systems/CustomTypes.hpp
  src/Client/Systems/CustomTypes/AnimRect.hpp
  src/Client/Systems/Events/EventsSystems.cpp
  src/Client/Systems/Menu/ButtonCallbacks.cpp
  src/Client/Systems/Menu/ButtonCallbacks.hpp
  src/Client/Systems/Menu/CMakeLists.txt
  src/Client/Systems/Menu/Menu.cpp
  src/Client/Systems/Menu/Menu.hpp
  src/Client/Systems/Menu/MenuSystems.cpp
  src/Client/Systems/Menu/MenuSystems.hpp
  src/ECS/Json.cpp
  src/ECS/Json.hpp
  src/main_client.cpp
Labels: documentation, enhancement

#131 Feature/rb 146 network lobby
  .github/workflows/compil.yml
  assets/Json/selectLobby.json
  scripts/compil.sh
  src/Client/SceneManager.hpp
  src/Client/Systems/CMakeLists.txt
  src/Client/Systems/ClientSystems.cpp
  src/Client/Systems/ClientSystems.hpp
  src/Client/Systems/Menu/ButtonCallbacks.cpp
  src/Client/Systems/Menu/MenuSystems.cpp
  src/Client/Systems/Menus/CMakeLists.txt
  src/Client/Systems/Menus/SelectLobby/CMakeLists.txt
  src/Client/Systems/Menus/SelectLobby/SelectLobbySystems.cpp
  src/Client/Systems/Menus/SelectLobby/SelectLobbySystems.hpp
  src/Client/Systems/Network/ClientNetwork.cpp
  src/Client/Systems/Network/ClientNetwork.hpp
  src/ECS/Json.hpp
  src/ECS/MessageTypes.h
  src/ECS/ResourcesManager.cpp
  src/ECS/ResourcesManager.hpp
  src/Nitwork/ANitwork.cpp
  src/Nitwork/ANitwork.hpp
  src/Nitwork/CMakeLists.txt
  src/Nitwork/Nitwork.h
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkMainServer.cpp
  src/Nitwork/NitworkMainServer.hpp
  src/Nitwork/NitworkServer.cpp
  src/Nitwork/NitworkServer.hpp
  src/Server/Systems/Network/CMakeLists.txt
  src/Server/Systems/Network/MainServerNetwork.cpp
  src/Server/Systems/Network/MainServerNetwork.hpp
  src/Server/Systems/Network/ServerNetwork.cpp
  src/ServerArgsHandling.hpp
  src/main_client.cpp
  src/main_server.cpp
Labels: enhancement

#132 GRAPHIC: add texture manager to not re create each sprite
  src/Client/Raylib/Audio/Audio.cpp
  src/Client/Raylib/Audio/Audio.hpp
  src/Client/Raylib/Graphics/Graphics.cpp
  src/Client/Raylib/Graphics/Graphics.hpp
  src/Client/Raylib/UnloadRaylib.cpp
  src/Client/SceneManager.cpp
Labels: enhancement

#133 Fix/rb 156 better readme
  assets/icons/xlrgb-logo.png
  docs/README.md
  docs/user-guide/installation/packaged-binary/gnu-linux.md
  docs/user-guide/installation/packaged-binary/macos.md
  docs/user-guide/installation/packaged-binary/windows.md
Labels: documentation

#136 ECS: Fix bug layers
  src/Client/Systems/Graphic/SpriteSystems.cpp
Labels: bug
