Repository X-R-G-B/R-Bus, pull requests merged in 2023-11, with the labels that each got.

#142 CLIENT-MENU: Create Servers from GUI / Add menu music
  assets/Audio/Musics/home.mp3
  assets/Json/createLobby.json
  assets/Json/createServer.json
  assets/Json/menu.json
  assets/Json/selectLobby.json
  src/Client/Systems/Menus/CMakeLists.txt
  src/Client/Systems/Menus/CreateServer/CMakeLists.txt
  src/Client/Systems/Menus/CreateServer/CreateServerSystems.cpp
  src/Client/Systems/Menus/CreateServer/CreateServerSystems.hpp
  src/Client/Systems/Menus/Menu/ButtonCallbacks.cpp
  src/Client/Systems/Menus/Menu/ButtonCallbacks.hpp
  src/Client/Systems/Menus/Menu/Menu.cpp
  src/Client/Systems/Menus/Menu/MenuSystems.cpp
  src/Client/Systems/Network/ClientNetwork.cpp
  src/Client/Systems/Parallax/Parallax.cpp
  src/Client/Systems/Parallax/Parallax.hpp
  src/Game/ResourcesManager.hpp
  src/Nitwork/NitworkClient.cpp
  src/Nitwork/NitworkClient.hpp
  src/Nitwork/NitworkMainServer.cpp
  src/Nitwork/NitworkServer.cpp
  src/init.cpp
  src/init.hpp
Labels: documentation, enhancement

#144 CLIENT-GAME: Fix redsource on windows
  src/Client/Systems/Menus/Menu/MenuSystems.cpp
  src/Game/ResourcesManager.hpp
Labels: bug

#145 Update README.md
  deps/bluga-graphics/CMakeLists.txt
  docs/README.md
Labels: documentation

#146 DOCUMENTATION: Add emojify to mdbook
  .github/workflows/documentation.yml
Labels: documentation
